
name: Deploy Site

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build (optional)
        run: echo "Add your build step here"
      - name: Deploy
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/mqbrown/mqbrown.github.io.git
          cp -r ./* mqbrown.github.io/
          cd mqbrown.github.io
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "deploy"
          git push
