name: Deploy Site

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy only site folder
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/MQBrown/mqbrown.github.io.git
          cd mqbrown.github.io

          # Remove old files
          rm -rf *

          # Copy ONLY site files
          cp -r ../site/* .

          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "deploy clean site" || echo "No changes to commit"
          git push
